# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.xhzb: debug
    org.springframework: warn
    org.springframework.ai: debug

# Spring配置
spring:
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.168:3306/xhzb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: heima123
  # redis 配置
  data:
    redis:
      # 地址
      host: 192.168.100.168
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password: 123456
      # 连接超时时间
      timeout: 10s
      jedis:
        pool:
          enabled: true
# Springdoc配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
  group-configs:
    - group: 'default'
      display-name: '测试模块'
      paths-to-match: '/**'
      packages-to-scan: com.xhzb
# oss的配置，要根据自己实际情况来进行修改
oss:
  endpoint: oss-cn-beijing.aliyuncs.com # 注意如果是广州的将beijing修改为guangzhou
  accessKeyId: ${OSS_ACCESS_KEY_ID}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
  bucketName: itheimaweb # 换成你自己的

huaweicloud:
  ak: E0SGN0Z7KZXHQ3FHY312
  sk: BZHNPHTXuJeuWefG7apv2sPrDVeNh5TwhEkAmjio
  #如果是上海一，请填写"cn-east-3"；如果是北京四，请填写"cn-north-4";
  regionId: cn-north-4
  endpoint: 6e8baa3c5a.st1.iotda-app.cn-north-4.myhuaweicloud.com
  projectId: 088ec8a2f2fe45c6bc03d88e8cb8cdc9
  #amqp相关配置
  host: 6e8baa3c5a.st1.iotda-app.cn-north-4.myhuaweicloud.com
  accessKey: b9bmr0Ie
  accessCode: KVw6O9pOTFjwv5lUJPPSA6YoKpJ5p2o2
  queueName: DefaultQueue
